# Generated by Django 5.2.4 on 2025-08-01 17:31

import chalets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=chalets.models.chalet_image_upload_path)),
                ('is_main', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chalet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chalets.chalet')),
            ],
            options={
                'verbose_name': 'Chalet Image',
                'verbose_name_plural': 'Chalet Images',
                'ordering': ['order', '-is_main', 'created_at'],
            },
        ),
    ]
