# Generated by Django 5.2 on 2025-08-21 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalets', '0002_chaletimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chalet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='chalets.chalet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'indexes': [models.Index(fields=['user'], name='chalets_fav_user_id_5af141_idx'), models.Index(fields=['chalet'], name='chalets_fav_chalet__23b124_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'chalet'), name='unique_user_chalet_favorite')],
            },
        ),
    ]
