# Generated by Django 5.2 on 2025-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profile_images/%Y/%m/'),
        ),
    ]
