# Generated by Django 5.2 on 2025-08-11 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalets', '0002_chaletimage'),
        ('messaging', '0002_alter_message_created_at_alter_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatroom',
            name='messaging_c_chalet__909bd1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_chalet',
            field=models.ForeignKey(blank=True, help_text='The most recent chalet from which this chat was initiated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='chalets.chalet', verbose_name='Last Chalet'),
        ),
        migrations.AddField(
            model_name='message',
            name='chalet',
            field=models.ForeignKey(blank=True, help_text='Optional reference to the chalet discussed in this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chalets.chalet', verbose_name='Chalet'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Renter'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_chalet'], name='messaging_c_last_ch_589e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chalet'], name='messaging_m_chalet__6f3250_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('renter', 'owner'), name='unique_renter_owner_chatroom'),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='chalet',
        ),
    ]
